name: Maintain GitHub Streak

on:
  schedule:
    - cron: "0 18 * * *"   # 11:30 PM IST (safe for India)
  workflow_dispatch:

jobs:
  auto-streak:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create daily commit
        run: |
          git config user.name "PranayFadtare"
          git config user.email "pranayfadtare7@gmail.com"

          mkdir -p streak
          echo "Last updated: $(date)" > streak/daily.txt

          git add streak/daily.txt
          git commit -m "Daily streak maintenance" || echo "No changes"
          git push
